
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"Evan-HelpRequest-create-db","number":45,"title":"Evan HelpRequest database table creation","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/45"},{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-ArticlesTable","number":44,"title":"Kelly articles table","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/44"},{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"Julia-MenuItemReview","number":43,"title":"MenuItemReview created entity & repo, database, DELETE, PUT, GET endpoints","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/43"}]
