
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanHelpRequestGet","number":51,"title":"Evan help request get","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/51"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-RecRequestsTable","number":50,"title":"Added Controller, Repository, Entity and GET for single, GET ALL, POST, UPDATE, DELETE","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/50"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanHelpRequestPut","number":49,"title":"Evan help request put","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/49"},{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-ArticlesController","number":48,"title":"Kelly articles controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/48"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"Evan-HelpRequestController","number":47,"title":"Evan help request controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/47"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"Kriteen-UCSBDiningCommonsMenuItem","number":46,"title":"Kriteen UCSBDiningCommonsMenuItem Database Table Creation","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/46"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"Evan-HelpRequest-create-db","number":45,"title":"Evan HelpRequest database table creation","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/45"},{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"Julia-MenuItemReview","number":43,"title":"MenuItemReview created entity & repo, database, DELETE, PUT, GET endpoints","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-2/pull/43"}]
